Create deb files for various Ubuntu/Debian releases (#558)
* Create deb files for various Ubuntu/Debian releases

* wip

* squash: Drops macos arm64 for now.

* wip: Adds version job in needs.

switch from github.ref to $GITHUB_REF

* wip: Use fetch-gh-release-asset.

Fetching release r1.1-20-g9e3c1183 from repo jitsi/libjitsi
Error: [getReleaseByTag] Unexpected response: 404

There is a release but no tag, and it tries to download from tag, not release.

* Revert "wip: Use fetch-gh-release-asset."

This reverts commit f3270afc9baeb7b6b32d92853f4eaedc9c61e6d3.

* wip: do not use draft as it does not create a tag.

* Drops arch branch and leave master for maven central release.

Co-authored-by: via GitHub Actions <dev@jitsi.org>
Co-authored-by: Дамян Минков <damencho@jitsi.org>